### ISSUE TITLE
[Fix/Feature] Prevent users from tricking others by deleting or editing their messages

### ISSUE THREAD

**Issue by nebneb0703** [GalaxySH/cr-counting-bot#26]
This behaviour can either count as foul and reset the behaviour, or it may just decrement the count (if it was the most recent one)

**Comment by GalaxySH** [comment]
This shouldn't be too hard, I will do this first.

> This behaviour can either count as foul and reset the behaviour
If by "reset" you mean reset the count, that's how it would work anyways.

> decrement the count (if it was the most recent one)
**Unless it would be preferred another way**, I think I will just count the
counting mistake in favor of the person who counted, and not punish the
person who tried to trick them, and save the counter. It will give a
warning, but nothing will happen to the count.

**Comment by GalaxySH** [comment]
With the coming pr this behavior will be on by default. The behavior also differs from the request in that it will not count as a foul immediately and will give the users 2 more tries, is this alright?

It currently does not care about someone messing up due to editing, and I think I could add that pretty easily, I guess we'll see how well this goes.
